### ISSUE TITLE
Error after installing clean MediaWiki 1.36

### ISSUE THREAD

**Issue by jpylypiw** [Gittenburg/Attachments#11]
Yesterday I installed a plain new MediaWiki 1.36 on my Debian Webserver.
Today I found your Extension and definitly want to use it since it perfectly solves my use case.
When I click on the "Attach" Button in the top right navigation I get the following Error / Stacktrace:

```
[af5fdafa9a6f6760f9637322] /index.php?title=xxx&action=attach Error: Call to a member function getBoolOption() on null

Backtrace:

from /var/www/wiki/includes/specials/SpecialUpload.php(700)
#0 /var/www/wiki/includes/specials/SpecialUpload.php(286): SpecialUpload->getWatchCheck()
#1 /var/www/wiki/includes/specials/SpecialUpload.php(245): SpecialUpload->getUploadForm()
#2 /var/www/wiki/extensions/Attachments/includes/AttachAction.php(37): SpecialUpload->execute(string)
#3 /var/www/wiki/extensions/Attachments/includes/AttachAction.php(10): SpecialAttach->execute(Title)
#4 /var/www/wiki/includes/MediaWiki.php(531): AttachAction->show()
#5 /var/www/wiki/includes/MediaWiki.php(315): MediaWiki->performAction(Article, Title)
#6 /var/www/wiki/includes/MediaWiki.php(913): MediaWiki->performRequest()
#7 /var/www/wiki/includes/MediaWiki.php(546): MediaWiki->main()
#8 /var/www/wiki/index.php(53): MediaWiki->run()
#9 /var/www/wiki/index.php(46): wfIndexMain()
#10 {main}
```

My custom configuration in `LocalSettings.php`:

```
### Custom Extensions ###
wfLoadExtension( 'Attachments' );

### Custom Settings ###
$wgAttachmentsNamespaces[NS_MAIN] = true;
$wgNamespacesWithSubpages[NS_MAIN] = 1;
$wgFileExtensions = [ 'png', 'gif', 'jpg', 'jpeg', 'webp', 'pdf' ];
```

Do you have any idea what I did wrong here?

**Comment by Gittenburg** [comment]
Thanks for reporting this. You didn't do anything wrong, the extension just hasn't been tested yet with 1.36.

This bug should be fixed with d9576c4b848119d47055d28234fbc0148c73fbd1. Please let me know if you encounter any other problems.

Nice to hear that it solves your use case :)
