### ISSUE TITLE
Debug log messages with MediaWiki 1.36.1

### ISSUE THREAD

**Issue by andrewdbate** [Gittenburg/Attachments#13]
I am getting the following exceptions in the debug log file when using the Attachments extension with MediaWiki 1.36.1.
```
[GlobalTitleFail] MessageCache::parse called with no title set.
#0 /var/www/html/includes/language/Message.php(1331): MessageCache->parse(string, NULL, boolean, boolean, Language)
#1 /var/www/html/includes/language/Message.php(922): Message->parseText(string)
#2 /var/www/html/includes/language/Message.php(953): Message->format(string)
#3 [internal function]: Message->__toString()
#4 /var/www/html/includes/libs/HtmlArmor.php(58): htmlspecialchars(Message, integer)
#5 /var/www/html/includes/linker/LinkRenderer.php(313): HtmlArmor::getHtml(Message)
#6 /var/www/html/includes/linker/LinkRenderer.php(215): MediaWiki\Linker\LinkRenderer->buildAElement(Title, Message, array, boolean)
#7 /var/www/html/includes/linker/LinkRenderer.php(238): MediaWiki\Linker\LinkRenderer->makePreloadedLink(Title, Message, string, array, array)
#8 /var/www/html/extensions/Attachments/includes/Attachments.php(155): MediaWiki\Linker\LinkRenderer->makeKnownLink(Title, Message, array, array)
#9 /var/www/html/extensions/Attachments/includes/AttachmentsHooks.php(64): Attachments::makeList(Title, array, array, RequestContext)
#10 /var/www/html/includes/HookContainer/HookContainer.php(338): AttachmentsHooks::onBeforePageDisplay(OutputPage, SkinVector)
#11 /var/www/html/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#12 /var/www/html/includes/HookContainer/HookRunner.php(1000): MediaWiki\HookContainer\HookContainer->run(string, array, array)
#13 /var/www/html/includes/OutputPage.php(2629): MediaWiki\HookContainer\HookRunner->onBeforePageDisplay(OutputPage, SkinVector)
#14 /var/www/html/includes/MediaWiki.php(927): OutputPage->output(boolean)
#15 /var/www/html/includes/MediaWiki.php(940): MediaWiki::{closure}()
#16 /var/www/html/includes/MediaWiki.php(546): MediaWiki->main()
#17 /var/www/html/index.php(53): MediaWiki->run()
#18 /var/www/html/index.php(46): wfIndexMain()
#19 {main}
```
```
[GlobalTitleFail] MessageCache::parse called with no title set.
#0 /var/www/html/includes/language/Message.php(1331): MessageCache->parse(string, NULL, boolean, boolean, Language)
#1 /var/www/html/includes/language/Message.php(922): Message->parseText(string)
#2 /var/www/html/includes/language/Message.php(953): Message->format(string)
#3 /var/www/html/extensions/Attachments/includes/AttachmentsHooks.php(71): Message->__toString()
#4 /var/www/html/includes/HookContainer/HookContainer.php(338): AttachmentsHooks::onBeforePageDisplay(OutputPage, SkinVector)
#5 /var/www/html/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#6 /var/www/html/includes/HookContainer/HookRunner.php(1000): MediaWiki\HookContainer\HookContainer->run(string, array, array)
#7 /var/www/html/includes/OutputPage.php(2629): MediaWiki\HookContainer\HookRunner->onBeforePageDisplay(OutputPage, SkinVector)
#8 /var/www/html/includes/MediaWiki.php(927): OutputPage->output(boolean)
#9 /var/www/html/includes/MediaWiki.php(940): MediaWiki::{closure}()
#10 /var/www/html/includes/MediaWiki.php(546): MediaWiki->main()
#11 /var/www/html/index.php(53): MediaWiki->run()
#12 /var/www/html/index.php(46): wfIndexMain()
#13 {main}
```
```
[GlobalTitleFail] MessageCache::parse called with no title set.
#0 /var/www/html/includes/language/Message.php(1331): MessageCache->parse(string, NULL, boolean, boolean, Language)
#1 /var/www/html/includes/language/Message.php(922): Message->parseText(string)
#2 /var/www/html/includes/language/Message.php(953): Message->format(string)
#3 /var/www/html/extensions/Attachments/includes/AttachmentsHooks.php(116): Message->__toString()
#4 /var/www/html/includes/HookContainer/HookContainer.php(338): AttachmentsHooks::onSkinTemplateNavigation(SkinVector, array)
#5 /var/www/html/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#6 /var/www/html/includes/HookContainer/HookRunner.php(3589): MediaWiki\HookContainer\HookContainer->run(string, array, array)
#7 /var/www/html/includes/skins/SkinTemplate.php(1090): MediaWiki\HookContainer\HookRunner->onSkinTemplateNavigation(SkinVector, array)
#8 /var/www/html/skins/Vector/includes/SkinVector.php(173): SkinTemplate->buildContentNavigationUrls()
#9 /var/www/html/includes/skins/SkinMustache.php(136): SkinVector->getTemplateData()
#10 /var/www/html/includes/skins/SkinTemplate.php(146): SkinMustache->generateHTML()
#11 /var/www/html/includes/OutputPage.php(2634): SkinTemplate->outputPage()
#12 /var/www/html/includes/MediaWiki.php(927): OutputPage->output(boolean)
#13 /var/www/html/includes/MediaWiki.php(940): MediaWiki::{closure}()
#14 /var/www/html/includes/MediaWiki.php(546): MediaWiki->main()
#15 /var/www/html/index.php(53): MediaWiki->run()
#16 /var/www/html/index.php(46): wfIndexMain()
#17 {main}
```
```
[GlobalTitleFail] MessageCache::parse called with no title set.
#0 /var/www/html/includes/language/Message.php(1331): MessageCache->parse(string, NULL, boolean, boolean, Language)
#1 /var/www/html/includes/language/Message.php(922): Message->parseText(string)
#2 /var/www/html/includes/language/Message.php(953): Message->format(string)
#3 /var/www/html/extensions/Attachments/includes/AttachmentsHooks.php(117): Message->__toString()
#4 /var/www/html/includes/HookContainer/HookContainer.php(338): AttachmentsHooks::onSkinTemplateNavigation(SkinVector, array)
#5 /var/www/html/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#6 /var/www/html/includes/HookContainer/HookRunner.php(3589): MediaWiki\HookContainer\HookContainer->run(string, array, array)
#7 /var/www/html/includes/skins/SkinTemplate.php(1090): MediaWiki\HookContainer\HookRunner->onSkinTemplateNavigation(SkinVector, array)
#8 /var/www/html/skins/Vector/includes/SkinVector.php(173): SkinTemplate->buildContentNavigationUrls()
#9 /var/www/html/includes/skins/SkinMustache.php(136): SkinVector->getTemplateData()
#10 /var/www/html/includes/skins/SkinTemplate.php(146): SkinMustache->generateHTML()
#11 /var/www/html/includes/OutputPage.php(2634): SkinTemplate->outputPage()
#12 /var/www/html/includes/MediaWiki.php(927): OutputPage->output(boolean)
#13 /var/www/html/includes/MediaWiki.php(940): MediaWiki::{closure}()
#14 /var/www/html/includes/MediaWiki.php(546): MediaWiki->main()
#15 /var/www/html/index.php(53): MediaWiki->run()
#16 /var/www/html/index.php(46): wfIndexMain()
#17 {main}
```
```
[GlobalTitleFail] MessageCache::parse called with no title set.
#0 /var/www/html/includes/language/Message.php(1331): MessageCache->parse(string, NULL, boolean, boolean, Language)
#1 /var/www/html/includes/language/Message.php(922): Message->parseText(string)
#2 /var/www/html/includes/language/Message.php(953): Message->format(string)
#3 /var/www/html/extensions/Attachments/includes/AttachmentsHooks.php(116): Message->__toString()
#4 /var/www/html/includes/HookContainer/HookContainer.php(338): AttachmentsHooks::onSkinTemplateNavigation(SkinVector, array)
#5 /var/www/html/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#6 /var/www/html/includes/HookContainer/HookRunner.php(3589): MediaWiki\HookContainer\HookContainer->run(string, array, array)
#7 /var/www/html/includes/skins/SkinTemplate.php(1090): MediaWiki\HookContainer\HookRunner->onSkinTemplateNavigation(SkinVector, array)
#8 /var/www/html/includes/skins/SkinMustache.php(206): SkinTemplate->buildContentNavigationUrls()
#9 /var/www/html/includes/skins/SkinMustache.php(198): SkinMustache->getPortletsTemplateData()
#10 /var/www/html/skins/Vector/includes/SkinVector.php(177): SkinMustache->getTemplateData()
#11 /var/www/html/includes/skins/SkinMustache.php(136): SkinVector->getTemplateData()
#12 /var/www/html/includes/skins/SkinTemplate.php(146): SkinMustache->generateHTML()
#13 /var/www/html/includes/OutputPage.php(2634): SkinTemplate->outputPage()
#14 /var/www/html/includes/MediaWiki.php(927): OutputPage->output(boolean)
#15 /var/www/html/includes/MediaWiki.php(940): MediaWiki::{closure}()
#16 /var/www/html/includes/MediaWiki.php(546): MediaWiki->main()
#17 /var/www/html/index.php(53): MediaWiki->run()
#18 /var/www/html/index.php(46): wfIndexMain()
#19 {main}
```
```
[GlobalTitleFail] MessageCache::parse called with no title set.
#0 /var/www/html/includes/language/Message.php(1331): MessageCache->parse(string, NULL, boolean, boolean, Language)
#1 /var/www/html/includes/language/Message.php(922): Message->parseText(string)
#2 /var/www/html/includes/language/Message.php(953): Message->format(string)
#3 /var/www/html/extensions/Attachments/includes/AttachmentsHooks.php(117): Message->__toString()
#4 /var/www/html/includes/HookContainer/HookContainer.php(338): AttachmentsHooks::onSkinTemplateNavigation(SkinVector, array)
#5 /var/www/html/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#6 /var/www/html/includes/HookContainer/HookRunner.php(3589): MediaWiki\HookContainer\HookContainer->run(string, array, array)
#7 /var/www/html/includes/skins/SkinTemplate.php(1090): MediaWiki\HookContainer\HookRunner->onSkinTemplateNavigation(SkinVector, array)
#8 /var/www/html/includes/skins/SkinMustache.php(206): SkinTemplate->buildContentNavigationUrls()
#9 /var/www/html/includes/skins/SkinMustache.php(198): SkinMustache->getPortletsTemplateData()
#10 /var/www/html/skins/Vector/includes/SkinVector.php(177): SkinMustache->getTemplateData()
#11 /var/www/html/includes/skins/SkinMustache.php(136): SkinVector->getTemplateData()
#12 /var/www/html/includes/skins/SkinTemplate.php(146): SkinMustache->generateHTML()
#13 /var/www/html/includes/OutputPage.php(2634): SkinTemplate->outputPage()
#14 /var/www/html/includes/MediaWiki.php(927): OutputPage->output(boolean)
#15 /var/www/html/includes/MediaWiki.php(940): MediaWiki::{closure}()
#16 /var/www/html/includes/MediaWiki.php(546): MediaWiki->main()
#17 /var/www/html/index.php(53): MediaWiki->run()
#18 /var/www/html/index.php(46): wfIndexMain()
#19 {main}
```
```
[GlobalTitleFail] MessageCache::parse called with no title set.
#0 /var/www/html/includes/language/Message.php(1331): MessageCache->parse(string, NULL, boolean, boolean, Language)
#1 /var/www/html/includes/language/Message.php(922): Message->parseText(string)
#2 /var/www/html/includes/language/Message.php(953): Message->format(string)
#3 [internal function]: Message->__toString()
#4 /var/www/html/includes/skins/Skin.php(2356): htmlspecialchars(Message)
#5 /var/www/html/includes/skins/Skin.php(2498): Skin->makeLink(string, array, array)
#6 /var/www/html/includes/skins/SkinMustache.php(84): Skin->makeListItem(string, array)
#7 /var/www/html/skins/Vector/includes/SkinVector.php(371): SkinMustache->getPortletData(string, array)
#8 /var/www/html/includes/skins/SkinMustache.php(243): SkinVector->getPortletData(string, array)
#9 /var/www/html/includes/skins/SkinMustache.php(198): SkinMustache->getPortletsTemplateData()
#10 /var/www/html/skins/Vector/includes/SkinVector.php(177): SkinMustache->getTemplateData()
#11 /var/www/html/includes/skins/SkinMustache.php(136): SkinVector->getTemplateData()
#12 /var/www/html/includes/skins/SkinTemplate.php(146): SkinMustache->generateHTML()
#13 /var/www/html/includes/OutputPage.php(2634): SkinTemplate->outputPage()
#14 /var/www/html/includes/MediaWiki.php(927): OutputPage->output(boolean)
#15 /var/www/html/includes/MediaWiki.php(940): MediaWiki::{closure}()
#16 /var/www/html/includes/MediaWiki.php(546): MediaWiki->main()
#17 /var/www/html/index.php(53): MediaWiki->run()
#18 /var/www/html/index.php(46): wfIndexMain()
#19 {main}
```
The version of the Attachments extension I am using as the `master` branch at commit `d9576c4`.

The above exceptions were extracted from the debug log. I have enabled the debug log for by wiki by setting `$wgDebugLogFile = "/tmp/mediawiki-debug.log";` in my `LocalSettings.php` file.

Note that all of the above exceptions were printed to the log when loading a single page (i.e., I deleted the log file `/tmp/mediawiki-debug.log`, hard reloaded a single page, and then copied the exceptions from the log).

I do not know whether these exceptions also occur on 1.35 (the older release of MediaWiki). The above occurs on MediaWiki 1.36.1.

**Comment by Gittenburg** [comment]
Hey Andrew! These aren't exceptions, these are just debug log messages with stack traces.

Fixed for most cases with 8837342621edee9aa436f418a957c2e89a81fdf2. `wfMessage()` is still called in two static functions, so you might still sometimes see a GlobalTitleFail caused by Attachments in your debug log but it should be less frequent.
