### ISSUE TITLE
Exception when attaching file with latest version

### ISSUE THREAD

**Issue by andrewdbate** [Gittenburg/Attachments#14]
I've updated to the latest version (commit 8837342) which was to fix the stack traces I reported in #13.

However, now I am getting the following exception when I try to attach a new file to a page:
```
[97dbf556e9fd27593b2279a9] /wiki/File:TestPage_-_Manning.png Error: Call to undefined method Parser::msg()

Backtrace:

from /var/www/html/extensions/Attachments/includes/AttachmentsHooks.php(23)
#0 /var/www/html/includes/parser/Parser.php(3356): AttachmentsHooks::renderAttach(Parser, string)
#1 /var/www/html/includes/parser/Parser.php(3041): Parser->callParserFunction(PPFrame_Hash, string, array)
#2 /var/www/html/includes/parser/PPFrame_Hash.php(263): Parser->braceSubstitution(array, PPFrame_Hash)
#3 /var/www/html/includes/parser/Parser.php(2879): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)
#4 /var/www/html/includes/parser/Parser.php(1549): Parser->replaceVariables(string)
#5 /var/www/html/includes/parser/Parser.php(639): Parser->internalParse(string)
#6 /var/www/html/includes/content/WikitextContent.php(375): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#7 /var/www/html/includes/content/AbstractContent.php(591): WikitextContent->fillParserOutput(Title, integer, ParserOptions, boolean, ParserOutput)
#8 /var/www/html/includes/Revision/RenderedRevision.php(263): AbstractContent->getParserOutput(Title, integer, ParserOptions, boolean)
#9 /var/www/html/includes/Revision/RenderedRevision.php(235): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(WikitextContent, boolean)
#10 /var/www/html/includes/Revision/RevisionRenderer.php(217): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string, array)
#11 /var/www/html/includes/Revision/RevisionRenderer.php(154): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#12 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#13 /var/www/html/includes/Revision/RenderedRevision.php(197): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#14 /var/www/html/includes/poolcounter/PoolWorkArticleView.php(137): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#15 /var/www/html/includes/poolcounter/PoolCounterWork.php(162): PoolWorkArticleView->doWork()
#16 /var/www/html/includes/page/ParserOutputAccess.php(281): PoolCounterWork->execute()
#17 /var/www/html/includes/page/Article.php(746): MediaWiki\Page\ParserOutputAccess->getParserOutput(WikiFilePage, ParserOptions, MediaWiki\Revision\RevisionStoreCacheRecord, integer)
#18 /var/www/html/includes/page/Article.php(561): Article->generateContentOutput(User, ParserOptions, integer, OutputPage, array)
#19 /var/www/html/includes/page/ImagePage.php(153): Article->view()
#20 /var/www/html/includes/actions/ViewAction.php(74): ImagePage->view()
#21 /var/www/html/includes/MediaWiki.php(531): ViewAction->show()
#22 /var/www/html/includes/MediaWiki.php(315): MediaWiki->performAction(ImagePage, Title)
#23 /var/www/html/includes/MediaWiki.php(913): MediaWiki->performRequest()
#24 /var/www/html/includes/MediaWiki.php(546): MediaWiki->main()
#25 /var/www/html/index.php(53): MediaWiki->run()
#26 /var/www/html/index.php(46): wfIndexMain()
#27 {main}
```

Note that I have show exception details enabled in my `LocalSettings.php`:
```
$wgShowExceptionDetails = true;
```

Does the latest commit 8837342 work for you on your MediaWiki install?

**Comment by andrewdbate** [comment]
When I revert back to commit d9576c4 of the Attachments extension, I don't get the exception. So I assume there is a problem with the most recent commit.
