### ISSUE TITLE
MediaWiki 1.35.1 (PostgreSQL 10.15): ERROR: column "defaultsort" does not exist

### ISSUE THREAD

**Issue by dabble** [Gittenburg/Attachments#2]
This wiki is newly installed 1.35.1 with PostgreSQL 10.15.
I added the Attachments plugin to the extensions folder after first configuring the base wiki functionality and after I imported some pages.

I added the following to LocalSettings.php to enable the Attachments plugin.

```
$wgAttachmentsNamespaces[NS_MAIN] = true;
$wgNamespacesWithSubpages[NS_MAIN] = 1;
$wgShowExceptionDetails = true;
$wgShowDBErrorBacktrace = true;
$wgShowSQLErrors = true;

wfLoadExtension( 'Attachments' );
```

I only get this error message when Attachments is loaded.

```
[YAh@tYTybNHRwAq0rq-xdQAAAAM] /mediawiki/index.php?title=Main_Page Wikimedia\Rdbms\DBQueryError from line 1699 of /var/www/html/mediawiki-1.35.1/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading?

Error 42703: ERROR: column "defaultsort" does not exist
LINE 1: ...aultsort.pp_page) AND (pp_defaultsort.pp_propname="defaultso...
^

Function: Attachments::getPages
Query: SELECT page_title,page_namespace,purl.pp_value,pp_defaultsort.pp_value AS "defaultsort" FROM "page" INNER JOIN "revision" "rev" ON ((page_latest=rev_id) AND (rev_deleted=0)) LEFT JOIN "page_props" "patt" ON ((page_id=patt.pp_page) AND patt.pp_propname = 'attach-9565814d5d564fa898dd6111b94fae0b') LEFT JOIN "page_props" "purl" ON ((page_id=purl.pp_page) AND purl.pp_propname = 'attachments-url') LEFT JOIN "page_props" "pp_defaultsort" ON ((page_id=pp_defaultsort.pp_page) AND (pp_defaultsort.pp_propname="defaultsort")) WHERE (((page_title LIKE 'Main`_Page/%' ESCAPE '`' ) AND page_namespace = 0) OR (patt.pp_propname is not null)) AND (page_is_redirect = 0) AND (page_namespace !=6)

Backtrace:

#0 /var/www/html/mediawiki-1.35.1/includes/libs/rdbms/database/Database.php(1683): Wikimedia\Rdbms\Database->getQueryException()
#1 /var/www/html/mediawiki-1.35.1/includes/libs/rdbms/database/Database.php(1658): Wikimedia\Rdbms\Database->getQueryExceptionAndLog()
#2 /var/www/html/mediawiki-1.35.1/includes/libs/rdbms/database/Database.php(1227): Wikimedia\Rdbms\Database->reportQueryError()
#3 /var/www/html/mediawiki-1.35.1/includes/libs/rdbms/database/Database.php(1907): Wikimedia\Rdbms\Database->query()
#4 /var/www/html/mediawiki-1.35.1/includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->select()
#5 /var/www/html/mediawiki-1.35.1/includes/libs/rdbms/database/DBConnRef.php(313): Wikimedia\Rdbms\DBConnRef->__call()
#6 /var/www/html/mediawiki-1.35.1/extensions/Attachments/includes/Attachments.php(88): Wikimedia\Rdbms\DBConnRef->select()
#7 /var/www/html/mediawiki-1.35.1/extensions/Attachments/includes/AttachmentsHooks.php(62): Attachments::getPages()
#8 /var/www/html/mediawiki-1.35.1/includes/HookContainer/HookContainer.php(320): AttachmentsHooks::onBeforePageDisplay()
#9 /var/www/html/mediawiki-1.35.1/includes/HookContainer/HookContainer.php(131): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#10 /var/www/html/mediawiki-1.35.1/includes/HookContainer/HookRunner.php(991): MediaWiki\HookContainer\HookContainer->run()
#11 /var/www/html/mediawiki-1.35.1/includes/OutputPage.php(2610): MediaWiki\HookContainer\HookRunner->onBeforePageDisplay()
#12 /var/www/html/mediawiki-1.35.1/includes/MediaWiki.php(947): OutputPage->output()
#13 /var/www/html/mediawiki-1.35.1/includes/MediaWiki.php(960): MediaWiki->{closure}()
#14 /var/www/html/mediawiki-1.35.1/includes/MediaWiki.php(543): MediaWiki->main()
#15 /var/www/html/mediawiki-1.35.1/index.php(53): MediaWiki->run()
#16 /var/www/html/mediawiki-1.35.1/index.php(46): wfIndexMain()
#17 {main}
```

**Comment by Gittenburg** [comment]
Thanks for reporting this! I just pushed 0c398d14fb4ab8b3247c1c713c25ed5992966eea which should fix this bug, can you confirm that it works?

**Comment by dabble** [comment]
That did the trick.  Thank you!
